### ISSUE TITLE
Feature Request:  Allow Configuration for Multiple Tenants

### ISSUE THREAD

**Issue by DjTamotsu** [jenkinsci/fortify-on-demand-uploader-plugin#21]
I support more than one team using the same Jenkins master.  It would be very useful to have the ability to configure the plugin for use with multiple tenants.

**Comment by mtgibbs** [comment]
This kind of support leads to scenarios where sensitive data could bleed between tenants and undermines the tenant based system to protect this data from falling into the wrong hands.  One improperly configured upload and you'd expose every vulnerability of the code base to another person or team.   If the scenario is that these teams are separated into multiple tenants, there is probably a concern for that data to be entirely separate.

My suggestion would be to silo these different teams into separate Jenkins instances and configure them separately OR discuss combining these teams into one tenant and using FoD's permission model keep their applications separate.
