### ISSUE TITLE
EMEA and AMS | Assessment type issue when starting scans

### ISSUE THREAD

**Issue by cripher** [jenkinsci/fortify-on-demand-uploader-plugin#30]
Hi Team, 

Please see possible defect that we have discovered. 

Issue: 
1. When starting a static subscription scan in EMEA, the scan is starting as single static scan. 
2. When starting a static single scan in AMS, the scan is starting as subscription. 

Replicated as follow: 
1. Configured my Jenkins plugin to start a scan. 
2. Configured my post-build as seen in the screenshots attached. 
3. Started the build. 
4. Successfully started the scan. 
4. Checked the console output. 

Expected output: 
A. In EMEA, I started a subscription scan and the scan will start as a subscription. 
B. In AMS, I started a single scan and the scan will start as a single scan. 

Actual output: 
A. In EMEA, I started a subscription scan yet it started as a single scan. 
B. In AMS, I started a single scan yet it started as a subscription scan. 

Note: 
- Will also test in AUS and APJ to check if the behavior is also the same. 

Should you have any questions and concerns, please do not hesitate to reach out. 

Thanks,

![emea - tenant subscription scan](https://cloud.githubusercontent.com/assets/23040498/23801912/b08eb8f0-05ec-11e7-9cad-c912825d2b95.png)
![emea - tenant single scan](https://cloud.githubusercontent.com/assets/23040498/23801911/b08e640e-05ec-11e7-8723-8e5464dc2a3b.png)
![emea - subscription](https://cloud.githubusercontent.com/assets/23040498/23801913/b0920014-05ec-11e7-874c-a0b1ab1b9347.png)
![emea - single](https://cloud.githubusercontent.com/assets/23040498/23801914/b095d5e0-05ec-11e7-9605-e61eef809202.png)
![emea - scans](https://cloud.githubusercontent.com/assets/23040498/23801915/b099c240-05ec-11e7-9dc5-6278b330dcf9.png)
![ams - tenant portal subscription](https://cloud.githubusercontent.com/assets/23040498/23801916/b09c995c-05ec-11e7-85fa-793dfdf25c1d.png)
![ams - tenant portal single](https://cloud.githubusercontent.com/assets/23040498/23801917/b0bd2816-05ec-11e7-8c2a-f15e1dcaa17a.png)
![ams - subscription](https://cloud.githubusercontent.com/assets/23040498/23801918/b0c56a62-05ec-11e7-94f5-9b6b5a6cd71e.png)
![ams - scans](https://cloud.githubusercontent.com/assets/23040498/23801919/b0cd9c00-05ec-11e7-9531-aecbd429c408.png)

**Comment by mtgibbs** [comment]
Configuration setup has changed in 3.0.  @cripher If you still have this problem, please reopen this.
