### ISSUE TITLE
Tech Stacks with no language level

### ISSUE THREAD

**Issue by reggiebIV** [jenkinsci/fortify-on-demand-uploader-plugin#32]
When you have a tech stack with no language level associated (such as XML/HTML) the only option in the dropdown is N/A and the option value is set to "null" which leads to a null pointer exception when the build action runs.

**Comment by rageshns** [comment]
HP FoD jenkins plugins currently not supporting java script file uploading.There is no option for JS file uploading

**Comment by mtgibbs** [comment]
@reggiebIV We're internally testing a new approach to how you set up and configure builds.  Once we're happy with it and it at least suits our needs, we'll be publishing a new 3.0 version.  This will fix your particular error.

@rageshns Please open a new issue for tracking support for all of the existing FoD Technology Stacks

**Comment by cripher** [comment]
In addition to what @rageshns reported, JS is now part of XML/HTML technology stack. If they select XML/HTML as a possible workaround, it will only lead to what @reggiebIV reported.
