### ISSUE TITLE
Add support for authentication with username/password

### ISSUE THREAD

**Issue by rioseco23** [jenkinsci/fortify-on-demand-uploader-plugin#36]
The API key/secret pair is not too granular in terms of permissions, so some organizations would like their Jenkins plugin to be tied to an user's permissions, this would give them the ability to control better the access to the projects that Jenkins instance needs to "see"
Thanks,
Jose Gil

**Comment by mtgibbs** [comment]
Permissions will need to be handled better from FoD.  Version 3 removes this problem since all build configuration will be done through tokens from the FoD portal.  #37
