### ISSUE TITLE
Migrate API calls to V3 and add automatic entitlement ID logic

### ISSUE THREAD

**Issue by ryancblack** [jenkinsci/fortify-on-demand-uploader-plugin#5]
All calls should move to V3. Endpoints are generally very similar, excluding the need to specify entitlement ID on starting a scan.

This change allows manual specification of the desired entitlement to spend for a scan, but requires logic to automatically select one when needed.

This is done on the legacy endpoints by:
- First valid subscription
- Any valid single scan if no subscription
- Any single scan, even if there is no count available (may not succeed based on the option to "allow scanning without entitlement" for the account

https://api.hpfod.com/swagger/ui/index

**Comment by mtgibbs** [comment]
https://github.com/jenkinsci/fortify-on-demand-uploader-plugin/pull/12 addresses the V3 migration, but still makes the user specify the entitlement ID that they wish to use.

**Comment by mtgibbs** [comment]
#12 merged.  Let's track and open a new issue for future enhancements regarding entitlement usage.
