### ISSUE TITLE
"Assessment not found" error Jenkins Build

### ISSUE THREAD

**Issue by brocktubre** [jenkinsci/fortify-on-demand-uploader-plugin#55]
I have setup a Post-build action to trigger on a Jenkins build. When the build is triggered the FoD upload starts but I am receiving am "Assessment not found" error in the build Console Output. Any suggestion on how to fix this issue? Here are the results from the output:

```Starting FoD Upload.
Begin Create Zip.
Temporary file created at: /tmp/fodupload7621107053271435017.zip
End Create Zip.
Getting Assessment
Assessment not found
Build step 'Fortify on Demand Static Assessment' changed build result to UNSTABLE

**Comment by mtgibbs** [comment]
Hey Brock. It’s likely that your entitlement is not allowed for the choice of “subscription” or “single scan”. Did you check your entitlements? Which option did you choose?

**Comment by mtgibbs** [comment]
Now that I'm not on mobile.  @brocktubre 

This is most likely related to the discussion around #53 .  The user setting up the job will need to know what their entitlements are good for.  Some entitlements do not support both "Single Scan" and "Subscription" at the same time.  It is probably the case that you left the default option as "Single Scan" and the error message is bad.  I'll take a look at making better logging messages for that.

**Comment by brocktubre** [comment]
Okay, the issue seemed to be because the Jenkins build task setting of "Entitlement Preference" was set to "Single Scan" instead of "Subscription". Changing it to "Subscription" fixed the issue.

**Comment by mtgibbs** [comment]
:+1:
