### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by s4huey2012** [jenkinsci/fortify-on-demand-uploader-plugin#64]
While it should be self-evident that the build step be a post build step the wiki states “add a build step” for which there is not a FOD option, please update the documents to reflect "post build step"

Also the doc's states “Add Build Step **Fortify on Demand Upload** and configure the parameters following the help text provided.” Which is not the exact text used for the plugin, “Fortify on Demand Static Assessment", again should be obvious, but it was raised as an issue.

**Comment by yeulih** [comment]
Thank you for your input. The documentation was updated last week to reflect the latest version of the Jenkins Plugin.
