### ISSUE TITLE
HPE Security Fortify Assessment via Jenkins Job Builder 

### ISSUE THREAD

**Issue by rpkbajaj** [jenkinsci/fortify-on-demand-uploader-plugin#8]
Hi Team,

Can we have a support for HPE Security Fortify Assessment via Jenkins Job Builder [JJB – a python language for automated Jenkins job configuration]?

We are using below versions for our purposes:

Jenkins version: **1.596.2** 
HPE Security Fortify Jenkins Plugin version: **1.16.10**

**Comment by mtgibbs** [comment]
Hi @rpkbajaj, 

What plugin are you referring to in this issue?  You're talking about 1.16.10, but this plugin only goes as high as 1.10.

**Comment by mtgibbs** [comment]
Hey @rpkbajaj I'm closing this issue as you've not responded and I believe you to be talking about a different plugin anyways.

**Comment by rpkbajaj** [comment]
Hi,

Ok and Thank you. We used alternate way to fulfill our requirement so this
requirement can be closed for now.

Regards,
Ramanpreet
