### ISSUE TITLE
Issue with saving the new option 'inProgressScanActionType'

### ISSUE THREAD

**Issue by dra90n** [jenkinsci/fortify-on-demand-uploader-plugin#86]
There appears to be an issue with how the POST request to submit the config for the plugin is created. 

Other variables are sent with _. prefixes however inProgressScanActionType is not. 

Modifying the HTML form in Chrome prior to POSTing the request appears to resolve the issue.

The issue with code might be located:

fortify-on-demand-uploader-plugin/src/main/resources/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep/config.jelly lines 43-47 which doesn't match the other drop downs on line 37

**Comment by yeulih** [comment]
Can you confirm whether v5.0.0 resolves this issue?

**Comment by dra90n** [comment]
Looks like it's resolved it!
